import { readFile } from "node:fs/promises";

const researchUrl = new URL("../research/cafes-verified.json", import.meta.url);
const research = JSON.parse(await readFile(researchUrl, "utf8"));
const records = research.records;

function quote(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${String(value).replaceAll("'", "''")}'`;
}

function slugify(value) {
  return value
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/&/gu, " and ")
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-|-$/gu, "");
}

function verificationStatus(record) {
  return record.branchSpecificity === "explicit"
    ? "verified"
    : "branch-unspecified";
}

const unique = (values) => [...new Set(values)].sort();
const neighborhoods = unique(records.map(({ neighborhood }) => neighborhood));
const moods = unique(records.flatMap(({ moodTags }) => moodTags));
const offerings = unique(records.flatMap(({ offeringTags }) => offeringTags));
const ids = records.map(({ slug }) => quote(slug)).join(", ");

const sql = [
  "-- Generated by scripts/generate-d1-seed.mjs from research/cafes-verified.json.",
  "-- Regenerate this file; do not edit seed rows by hand.",
  "PRAGMA foreign_keys = ON;",
  "BEGIN TRANSACTION;",
  "",
  ...neighborhoods.map(
    (name) =>
      `INSERT INTO neighborhoods (slug, name) VALUES (${quote(slugify(name))}, ${quote(name)}) ON CONFLICT(name) DO UPDATE SET slug = excluded.slug;`,
  ),
  "",
  ...moods.map(
    (slug) =>
      `INSERT INTO moods (slug, name) VALUES (${quote(slug)}, ${quote(slug)}) ON CONFLICT(slug) DO UPDATE SET name = excluded.name;`,
  ),
  "",
  ...offerings.map(
    (slug) =>
      `INSERT INTO offerings (slug, name) VALUES (${quote(slug)}, ${quote(slug)}) ON CONFLICT(slug) DO UPDATE SET name = excluded.name;`,
  ),
  "",
  ...records.map((record) => {
    const mapsUrl = `https://www.google.com/maps/search/?api=1&query=${record.latitude},${record.longitude}`;
    return `INSERT INTO cafes (id, slug, name, branch, address, address_verified, neighborhood_id, latitude, longitude, coordinate_confidence, branch_specificity, verification_status, attributes_json, recommendation, source_url, maps_url, verified_at, published) VALUES (${quote(record.slug)}, ${quote(record.slug)}, ${quote(record.name)}, ${quote(record.branch)}, ${quote(record.address)}, ${record.addressVerified ? 1 : 0}, (SELECT id FROM neighborhoods WHERE name = ${quote(record.neighborhood)}), ${quote(record.latitude)}, ${quote(record.longitude)}, ${quote(record.coordinateConfidence)}, ${quote(record.branchSpecificity)}, ${quote(verificationStatus(record))}, '[]', ${quote(record.recommendation)}, ${quote(record.sourceUrl)}, ${quote(mapsUrl)}, ${quote(record.verifiedAt)}, 1) ON CONFLICT(id) DO UPDATE SET slug = excluded.slug, name = excluded.name, branch = excluded.branch, address = excluded.address, address_verified = excluded.address_verified, neighborhood_id = excluded.neighborhood_id, latitude = excluded.latitude, longitude = excluded.longitude, coordinate_confidence = excluded.coordinate_confidence, branch_specificity = excluded.branch_specificity, verification_status = excluded.verification_status, attributes_json = excluded.attributes_json, recommendation = excluded.recommendation, source_url = excluded.source_url, maps_url = excluded.maps_url, verified_at = excluded.verified_at, published = excluded.published, updated_at = CURRENT_TIMESTAMP;`;
  }),
  "",
  `DELETE FROM cafe_moods WHERE cafe_id IN (${ids});`,
  `DELETE FROM cafe_offerings WHERE cafe_id IN (${ids});`,
  "",
  ...records.flatMap((record) =>
    record.moodTags.map(
      (mood) =>
        `INSERT INTO cafe_moods (cafe_id, mood_id) SELECT ${quote(record.slug)}, id FROM moods WHERE slug = ${quote(mood)} ON CONFLICT(cafe_id, mood_id) DO NOTHING;`,
    ),
  ),
  "",
  ...records.flatMap((record) =>
    record.offeringTags.map(
      (offering) =>
        `INSERT INTO cafe_offerings (cafe_id, offering_id) SELECT ${quote(record.slug)}, id FROM offerings WHERE slug = ${quote(offering)} ON CONFLICT(cafe_id, offering_id) DO NOTHING;`,
    ),
  ),
  "",
  "COMMIT;",
  "",
].join("\n");

process.stdout.write(sql);
